### ISSUE TITLE
Harvest function error when NA introduced

### ISSUE THREAD

**Issue by RossPitman** [cttedwards/leopard#10]
I'm busy testing a range of simulations, but often receive the error message: _Error in if (size > 0) { : missing value where TRUE/FALSE needed._

This seems to occur within the harvest function, and appears to be the result of a particular age class going extinct. Is there any way that the harvest function could accommodate instances when age classes go extinct? Perhaps, if there are too few individuals in an age class to remove based on the quota, the model just removes those remaining individuals. Then if there aren't any individuals to remove, the model still continues.

The code used to generate the error can be found in sim.4.r

FYI - I also suspect the error has something to do with the cub and juvenile age classes.

**Comment by cttedwards** [comment]
the code doesn't run anymore (the package has been updated) but I think this is fixed now. Re-open if not.
